application:
  output-dir: /home/helge/dev/privat/trening/ENV/exchange
heart-rate:
  max: 191
  measured-activity: cycling/vo2max-test
  date: 2024-11-02
  zones:
  - Recovery: 0-115
  - Endurance: 115-138  
  - Tempo: 138-157
  - Lactate Threshold: 157-167
  - VO2max: 167-176
  - Anaerobic Capacity: 176-183
  - Neuromuscular Power: 184-
cycling: 
  ftp: 260
  power-zones: 
    - Recovery: 0-143
    - Endurance: 144-195
    - Tempo: 196-234
    - Treshold: 235-273
    - VO2 Max: 274-312
    - Anaerobic Capacity: 313-390
    - Neuromuscular: 391-
running:
  ftp: 365
  power-zones: 
    - Recovery: 0-255
    - Endurance: 255-290
    - Tempo: 290-330
    - Threshold: 330-385
    - VO2Max: 385-440
    - Anaerobic: 440-
autolap: PT10M
